// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "server/schema.prisma",
  migrations: {
    path: "server/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
